#!/usr/bin/env python
import cgi,re

fs = cgi.FieldStorage()

print "Content-type: text/plain\n"
# for key in fs.keys():
#     print "%s = %s" % (key, fs[key].value)

size=fs["size"].value
size = int(float(re.sub(r'[^\d.]+', '', size))\
	*(1+999*(re.match('.*[Kk].*',size) is not None))\
	*(1+999999*(re.match('.*[Mm].*',size) is not None)))

print str(size) + " bytes:\n"

print "x"*size