#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
      exit 1
fi

xl destroy pvm
xl create /etc/xen/pvm.cfg
killall ssh
killall gdbsx
domid=$(xl list | grep pvm | awk '{print $2}')

echo "New domain $domid"
echo "Run \"gdb -tui -ex 'target remote localhost:2222'\" to resume the VM"
gdbsx -a $domid 64 2222 &
