version: '2'
services:
  apache:
    image: patricknevindwyer/apache-harness:latest
    ports:
      - "9000:80"
  goloris:
    image: patricknevindwyer/goloris-harness:latest
    depends_on:
      - apache
    links:
      - apache
    command: /bin/bash -c 'sleep 20 ; /goloris -victimUrl="http://apache"'
  httperf:
    image: patricknevindwyer/httperf:latest
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./log/httperf:/var/log/httperf