version: '2'
services:
  apache:
    # image: patricknevindwyer/apache-harness:latest
    image: patricknevindwyer/pinned-apache:latest
    environment:
      LORIS_TEST_DURATION:
    ports:
      - "9000:80"
    volumes:
      - ./log/apacheperf:/var/log/apacheperf
      - ./log/apachepin:/root/output
    privileged: true
  goloris:
    image: patricknevindwyer/goloris-harness:latest
    environment:
      LORIS_TEST_DURATION:
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./log/goloris:/var/log/goloris
    command: /bin/bash -c 'sleep 2 ; /goloris -victimUrl="http://apache" -testDuration=0h0m${LORIS_TEST_DURATION}s &> /var/log/goloris/performance.log'
  httperf:
    image: patricknevindwyer/httperf:latest
    environment:
      LORIS_TEST_DURATION:
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./log/httperf:/var/log/httperf