version: '2'
network_mode: 'host'
services:
  apache:
    build: "./apache"
    ports:
      - "9000:80"
  goloris:
    build: "./goloris"
    depends_on:
      - apache
    links:
      - apache
    command: /goloris -victimUrl="http://apache"