
node {

    def IMAGE = "ta3-slow-loris"
    def REPO = "magicwand-mirror"

	slackSend channel: '#xd3-magicwand', message: "Building ${REPO}/${IMAGE} # ${env.BUILD_NUMBER}", teamDomain: 'invincealabs', token: 'IO6gEo9GXsCiperPGx0XPIKk'

	try {
		// clean previous instances of magicwand
		stage 'Clear old instances'

		sh "rm -rf ${REPO}"

		// checkout our content
		stage 'Checkout'

		sh "git -c http.sslVerify=false clone https://gitlab.labs/patrick.dwyer/${REPO}.git"

        dir(REPO) {
            dir ("test-harness") {
                stage "Downloading images"
                sh "docker pull patricknevindwyer/apache-harness:latest"
                sh "docker pull patricknevindwyer/goloris-harness:latest"

                stage "Docker Compose"

                sh "docker-compose up --no-build -d"

                stage "Collection 01"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 02"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 03"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 04"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 05"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 06"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 07"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 08"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 09"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Collection 10"

                sh "./stats.sh"
                sh "sleep 5"

                stage "Spin down"

                sh "docker-compose down"
            }
        }
		slackSend channel: '#xd3-magicwand', message: "Test ${REPO}/${IMAGE} # ${env.BUILD_NUMBER} succeeded", teamDomain: 'invincealabs', token: 'IO6gEo9GXsCiperPGx0XPIKk'
	}
	catch (err) {
		slackSend channel: '#xd3-magicwand', message: "Test ${REPO}/${IMAGE} # ${env.BUILD_NUMBER} failed", teamDomain: 'invincealabs', token: 'IO6gEo9GXsCiperPGx0XPIKk'
	}
}