#!/bin/bash 

if [ -z $PVM_IP ]; then
   echo "Failure: PVM_IP must be defined in env"
   exit 1
fi

if [ -z $PVM_USER ]; then
   echo "Failure: PVM_USER must be defined in env"
   exit 1
fi

if [ -z $MWROOT ]; then
   echo "Failure: MWROOT must be defined in env"
   exit 1
fi

docmd() {
   echo "Command: $*"
   $*
}

docmd scp -rq $MWROOT/protvm     $PVM_USER@$PVM_IP:
docmd scp -rq $MWROOT/common     $PVM_USER@$PVM_IP:
docmd scp -rq $MWROOT/util       $PVM_USER@$PVM_IP:
docmd scp -rq $MWROOT/exports    $PVM_USER@$PVM_IP:
