#!/bin/bash 

PVM_IP=192.168.0.19
PVM_USER=sluser
MWROOT="$HOME/proj/mw-cbb"

docmd() {
   echo "Command: $*"
   $*
}

# Try: rsync -r --delete 

docmd scp -rq $MWROOT/common $PVM_USER@$PVM_IP:
docmd scp -rq $MWROOT/protvm $PVM_USER@$PVM_IP:
#docmd rsync -r --delete $MWROOT/common $PVM_USER@$PVM_IP:
#docmd rsync -r --delete $MWROOT/protvm $PVM_USER@$PVM_IP:
