#!/bin/bash 

if [ -z $PVM_IP ]; then
   echo "Failure: PVM_IP must be defined in env"
   exit 1
fi

if [ -z $PVM_USER ]; then
   echo "Failure: PVM_USER must be defined in env"
   exit 1
fi

if [ -z $MWROOT ]; then
   echo "Failure: MWROOT must be defined in env"
   exit 1
fi

docmd() {
   echo "Command: $*"
   $*
}

COPY_CMD='rsync -avzr'

docmd ssh $PVM_USER@$PVM_IP mkdir -p $MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi


docmd $COPY_CMD  $MWROOT/protvm     $PVM_USER@$PVM_IP:$MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi

docmd $COPY_CMD $MWROOT/common     $PVM_USER@$PVM_IP:$MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi


docmd $COPY_CMD $MWROOT/util       $PVM_USER@$PVM_IP:$MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi

docmd $COPY_CMD $MWROOT/exports    $PVM_USER@$PVM_IP:$MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi

docmd $COPY_CMD $MWROOT/test $PVM_USER@$PVM_IP:$MWROOT
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi
