#!/bin/bash 

if [ -z $PVM_IP ]; then
   echo "Failure: PVM_IP must be defined in env"
   exit 1
fi

if [ -z $PVM_USER ]; then
   echo "Failure: PVM_USER must be defined in env"
   exit 1
fi

docmd() {
   echo "Command: $*"
   $*
}

docmd scp -rq $PVM_USER@$PVM_IP:common /tmp/mwpvm
docmd scp -rq $PVM_USER@$PVM_IP:protvm /tmp/mwpvm
