#!/bin/bash

if [ -z $PVM_IP ]; then
    echo "Failure: PVM_IP must be defined in env"
    exit 1
fi

if [ -z $PVM_USER ]; then
    echo "Failure: PVM_USER must be defined in env"
    exit 1
fi

if [ -z $MWROOT ]; then
    echo "Failure: MWROOT must be defined in env"
    exit 1
fi

ssh $PVM_USER@$PVM_IP rsync --version >/dev/null 2>&1
RC=$?
if [ $RC -ne 0 ]; then
    echo "Failure: rsync must be installed on system $PVM_IP"
    exit 1
fi

docmd() {
    echo "Command: $*"
    $*
}

COPY_CMD='rsync -avzr'

PVM_MWROOT="/home/${PVM_USER}/ins-production/magicwand-commsbackbone"

sudo mkdir -p /tmp/mwpvm

docmd $COPY_CMD $PVM_USER@$PVM_IP:$MWROOT/ /tmp/mwpvm
RC=$?
if [ $RC -ne 0 ]; then
    echo Error: $RC
    exit $RC
fi

cp $MWROOT/test/test_artifacts/gdbinit_mwcomms /tmp/mwpvm/protvm/kernel/mwcomms/.gdbinit
