#!/bin/bash 

## Prepare the repo for development copying some files to their final
## destinations. We do this on files that devs change frequently, so
## those changes aren't constantly shown in the repo history.


if [ -z $MWROOT ]; then
   echo "Failure: MWROOT must be defined in env"
   exit 1
fi

mt=Makefile.template
m=Makefile

# Copy the template Makefiles to regular Makefiles
for d in $MWROOT/unikernel/rump-xenevent/apps/xenevent_app \
         $MWROOT/protvm/user/wrapper \
         $MWROOT/protvm/kernel/char_driver; 
do
   cp $d/Makefile.template $d/Makefile
done


#cp $MWROOT/unikernel/rump-xenevent/apps/xenevent_app/$mt \
#   $MWROOT/unikernel/rump-xenevent/apps/xenevent_app/$m

#cp $MWROOT/protvm/user/wrapper/$mt $MWROOT/protvm/user/wrapper/$m

#cp $MWROOT/protvm/kernel/char_driver/$mt $MWROOT/protvm/kernel/char_driver/$m

cp $MWROOT/common/xen_keystore_defs.h.template $MWROOT/common/xen_keystore_defs.h