#!/bin/bash 

##
## Prepare the repo for development by copying some files to their
## final destinations. We do this on files that devs change
## frequently, so those changes aren't constantly changing in the
## repo.
##

if [ -z $MWROOT ]; then
   echo "Failure: MWROOT must be defined in env"
   exit 1
fi

# Copy the template Makefiles to regular Makefiles
for d in $MWROOT/ins/ins-rump/apps/ins-app           \
         $MWROOT/protvm/user/wrapper                 \
         $MWROOT/protvm/kernel/mwcomms               \
         $MWROOT/protvm/kernel/char_driver           \
         $MWROOT/ins/ins-rump/src-netbsd/sys/rump/dev/lib/libxenevent;
do
   cp $d/Makefile.template $d/Makefile
done


cp $MWROOT/common/common_config.h.template $MWROOT/common/common_config.h
