FROM 32bit/ubuntu:14.04
MAINTAINER patricknevindwyer@gmail.com

USER root

RUN cp /bin/uname /root/uname_old
ADD ./uname_override /root/uname
RUN chmod +x /root/uname
RUN ln -sf /root/uname /bin/uname

# install our basic toolset
RUN apt-get update
RUN apt-get install -y g++ wget make

RUN mkdir /root/tmp
RUN mkdir /root/pin

ADD ./pin/* /root/pin/
RUN mv /root/pin/apachectl32 /root/pin/apachectl

# Install apache
WORKDIR /root/tmp

RUN wget http://archive.apache.org/dist/httpd/httpd-2.2.11.tar.gz
RUN tar -zxvf httpd-2.2.11.tar.gz

WORKDIR /root/tmp/httpd-2.2.11
RUN ./configure
RUN make
RUN make install

# Setup python
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install --upgrade pip
RUN pip install baker

# Installing PIN
WORKDIR /root/tmp

RUN wget --no-check-certificate http://software.intel.com/sites/landingpage/pintool/downloads/pin-3.0-76991-gcc-linux.tar.gz
RUN tar -zxvf pin-3.0-76991-gcc-linux.tar.gz
RUN ln -s pin-3.0-76991-gcc-linux pin-current
RUN ln -s /root/tmp/pin-current/pin /bin/pin

# build a PIN tool
WORKDIR /root/pin

RUN mkdir obj-ia32
RUN make TARGET=ia32 PIN_ROOT=/root/tmp/pin-current obj-ia32/calltrace.so
RUN make TARGET=ia32 PIN_ROOT=/root/tmp/pin-current obj-ia32/calltrace_streaming.so

RUN ln -s /root/pin/apachectl /bin/apachectl
RUN chmod ugo+x /root/pin/apachectl

# setup trace output
RUN mkdir /root/output
RUN chmod ugo+rwx /root/output

# Set the output volume
VOLUME ["/root/output"]

CMD apachectl pin-foreground