#
# Standard no-strings-attched compilation of the test TCP/IP app and
# its accompanying shared library.  The shared library preloads the
# app and intercepts selected TCP/IP calls to the network stack.
# 

CC = gcc
CFLAGS = -Wall -Wno-missing-braces -fPIC -DPIC -pthread
CFLAGS += -I../../common
DEBUG = -ggdb

TCP_IP_APP_NAME=connection_test

all: $(TCP_IP_APP_NAME) 

$(TCP_IP_APP_NAME): $(TCP_IP_APP_NAME).c
	$(CC) $(DEBUG) $(CFLAGS) $^ -o $@ 

clean:
	rm -f $(TCP_IP_APP_NAME)
